scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ '127.0.0.1:9100' ]
  - job_name: 'thoth'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ '127.0.0.1:8080' ]
