-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    chat_id bigint NOT NULL,
    stack_addr character varying(128) NOT NULL,
    current_block_height bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.wallet_addresses
(
    id bigserial NOT NULL,
    addr character varying(128) NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.assets
(
    id bigserial NOT NULL,
    policy_id character varying(256)[] NOT NULL,
    asset_name character varying(512)[] NOT NULL,
    quantity integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.assets
	ADD CONSTRAINT unique_asset UNIQUE (policy_id, asset_name);

ALTER TABLE IF EXISTS public.wallet_addresses
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;